server:
  port: 9296

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        bootstrap: true
        git:
          uri: https://github.com/nigamkaushal/microservices-config-server
          skip-ssl-validation: true
          clone-on-start: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka