server:
  port: 9001

spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/department-service
    username: postgres
    password: pass
  application:
    name: DEPARTMENT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  config:
    import: "optional:configserver:http://localhost:9296"